language: cpp
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq python3 subversion
install:
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
compiler:
 - clang
 - gcc
addons:
 apt:
  sources:
  - ubuntu-toolchain-r-test
  packages:
  - gcc-4.8
  - g++-4.8
  - clang
script:
 - ./build.sh
 - cd tests
 - ./run.py
